---
name: "docker-build"

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  docker-build:
    uses: terraharbor/github-actions-workflows/.github/workflows/docker-build.yaml@main
    with:
      push_image: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      build_context: "."
      dockerfile_path: "Dockerfile"
    secrets:
      GITHUB_TOKEN_CALLER: ${{ secrets.GITHUB_TOKEN }}
